modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
[[mods]] #mandatory
modId="snowaccumulation" #mandatory
version="1.1" #mandatory
displayName="Snow Accumulation" #mandatory
logoFile="assets/snowaccumulation/textures/logo.png" #optional
authors="Crazy Crafter" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Makes snow accumulate
'''